name: churn_env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8*
  - scikit-learn=1.2*
  - pandas=1.5*
  - matplotlib=3.6*
  - seaborn=0.12*
  - jupyter=1.0*
  - shap=0.41*
  - black=22.6*
  - pytest=7.1*
  - pip=22.3*
  - black-jupyter=22.6*
  - pyyaml=6.0
  - pip:
    - typer[all]==0.7.0
    - -e .